### ISSUE TITLE
What does "supports Rich Text Formatting" mean?

### ISSUE THREAD

**Issue by sippeangelo** [nnaaa-vr/XSNotifications#2]
```C#
public string title = ""; //Notification title, supports Rich Text Formatting
public string content = ""; //Notification content, supports Rich Text Formatting, if left empty, notification will be small.
```

It doesn't seem to parse RTF at all
![image](https://user-images.githubusercontent.com/262378/114465393-5625ca80-9be7-11eb-9776-25961cbd40a5.png)

**Comment by nnaaa-vr** [comment]
It supports TextMesh Pro rich text. See these docs for details: http://digitalnativestudios.com/textmeshpro/docs/rich-text/

**Comment by sippeangelo** [comment]
> 
> 
> It supports TextMesh Pro rich text. See these docs for details: http://digitalnativestudios.com/textmeshpro/docs/rich-text/

Cool! Thanks!
